apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tank-senor
  name: tank-senor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tank-senor
  template:
    metadata:
      labels:
        app: tank-senor
    spec:
      containers:
      - image: sensor
        name: tank-sensor
        imagePullPolicy: Never
        env:
          - name: API_URL
            value: http://192.168.49.2:30009/api/ingest
