apiVersion: v1
kind: Service
metadata:
    name: frontend-service
spec:
    type: NodePort
    ports:
      - targetPort: 3000
        port: 3000
        nodePort: 30008
    selector:
        app: aqua-fe  
        type: front-end
